import pytest # imports the testing framework.pytest is the tool that finds and runs all the test functions automatically
from fastapi.testclient import TestClient # imports a special client that FastAPI provides specifically for testing. It simulates HTTP requests without actually starting the server.
from app.main import app ## imports the FastAPI app that i craeted so teh testClient can send requests to it.

client = TestClient(app)# creates a fake browser  so teh client can send POST,GET,PUT requests to your endpoints
# edge Case tests for auth endpoints
client = TestClient(app)

# Test with real email that exist in datbse but wrong password. to see if teh system correctly rejects wrong credentials. Expected 401
def test_wrong_password():
    response = client.post("/auth/login", json={
        "email": "ferdaws@gmail.com",
        "password": "Ferd"
    })
    assert response.status_code == 401
# test with an email doesnt exist in teh datbase at all. to see that the system doesn't give a hunt about which part is wrong email exists or not
def test_nonexistent_email():
    response = client.post("/auth/login", json={
        "email": "nferdaws@gmail.com",
        "password": "test1234"
    })
    assert response.status_code == 401
# try both email and password are wrong to see if the system correctly rejects it with 401 Unauthorized and doesn't give a hint about which part is wrong
def test_wrong_email_and_password():
    response = client.post("/auth/login", json={
        "email": "rtferd@gmail.com",
        "password": "jjjjj"
    })
    assert response.status_code == 401

# try to access /auth/me protected endpoint without sending any token at all to check if teh get_current_user dependency correctly blocks unautheticated requests and returns 401 Unauthorized
def test_access_protected_route_without_token():
    response = client.get("/auth/me")
    assert response.status_code == 401

# send a fake JWT tocken that was never generated by the system. we did this to test if token verification catches invalid tokens .Expected 401
def test_access_protected_route_with_fake_token():
    response = client.get("/auth/me", headers={
        "Authorization": "Bearer faketoken123"
    })
    assert response.status_code == 401
# Test using SQL injection attack because hackers try to inject SQL code into input fields bypass authentication
def test_sql_injection_attempt():
    response = client.post("/auth/login", json={
        "email": "admin' OR '1'='1",
        "password": "ferdss"
    })
    assert response.status_code == 422